#pragma once

namespace Fusion
{
	extern const uint8_t* _binary_C__Code_libFusionDriver_Build_ShellCode_LoaderShellCode_bin_start;
	extern const uint8_t* _binary_C__Code_libFusionDriver_Build_ShellCode_LoaderShellCode_bin_end;
	extern size_t _binary_C__Code_libFusionDriver_Build_ShellCode_LoaderShellCode_bin_size;

	extern const uint8_t* _binary_C__Code_libFusionDriver_Build_ShellCode_ThreadShellCode_bin_start;
	extern const uint8_t* _binary_C__Code_libFusionDriver_Build_ShellCode_ThreadShellCode_bin_end;
	extern size_t _binary_C__Code_libFusionDriver_Build_ShellCode_ThreadShellCode_bin_size;

	extern const uint8_t* _binary_C__Code_libFusionDriver_Build_ShellCode_UnLoaderShellCode_bin_start;
	extern const uint8_t* _binary_C__Code_libFusionDriver_Build_ShellCode_UnLoaderShellCode_bin_end;
	extern size_t _binary_C__Code_libFusionDriver_Build_ShellCode_UnLoaderShellCode_bin_size;
}